import { Geist, Inter, Poppins} from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import { ToastContainer } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const inter = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight:'600'
});

export const metadata = {
  title: "Tutors Booking System",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${inter.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar></Navbar>
        <main>
          {children}
        </main>
        <Footer></Footer>
        <ToastContainer/>
        </body>
    </html>
  );
}
