
import React from 'react';
import { Table } from '@heroui/react';


export const metadata = {
    title: "My Tutors",
    description: "Generated by create next app",
};



const MyTutorPage = async () => {
    const res = await fetch("http://localhost:7002/addtutor")
    const tutor = await res.json()
    console.log(tutor)
    return (
        <div className='max-x-7xl mx-auto px-4 py-6'>
            <h2 className='text-center text-2xl md:text-3xl font-bold mb-5'>My Tutor page</h2>
            <div className='container gap-3 mx-auto'>
                <Table variant="secondary">
                    <Table.ScrollContainer>
                        <Table.Content aria-label="Team members" className="min-w-[400px]">
                            <Table.Header>
                                <Table.Column isRowHeader>Tutor Name</Table.Column>
                                <Table.Column>Subject</Table.Column>
                                <Table.Column>Available</Table.Column>
                                <Table.Column>Hourly Fee</Table.Column>
                                <Table.Column>Total Slot</Table.Column>
                                <Table.Column>Registration Date</Table.Column>
                                <Table.Column>Action</Table.Column>

                            </Table.Header>
                            <Table.Body>
                                {
                                    tutor.map((tutor) =>
                                        <Table.Row key={tutor?._id}>
                                            <Table.Cell>{tutor?.name}</Table.Cell>
                                            <Table.Cell>{tutor?.category}</Table.Cell>
                                            <Table.Cell>{tutor?.day_times}</Table.Cell>
                                            <Table.Cell>{tutor?.fee}</Table.Cell>
                                            <Table.Cell>{tutor?.slot}</Table.Cell>
                                            <Table.Cell>{tutor?.startDate}</Table.Cell>

                                            <Table.Cell>
                                               
                                            </Table.Cell>
                                            {/* <Table.Cell><Button variant='outline' className={'bg-red-100 rounded-2xl text-red-400'}>X</Button></Table.Cell> */}
                                        </Table.Row>
                                    )
                                }
                            </Table.Body>
                        </Table.Content>
                    </Table.ScrollContainer>
                </Table>
            </div>
        </div>
    );
};

export default MyTutorPage;