import React from 'react';


export const metadata = {
  title: "My Tutors",
  description: "Generated by create next app",
};

const MyTutorPage = () => {
    return (
        <div>
            <h2>My Tutor page</h2>
        </div>
    );
};

export default MyTutorPage;